# Programação Python para Ciência de Dados

## Homework Numpy e Pandas - Parte I

In [ ]:
import numpy as np
import pandas as pd

#### 1) Leia o arquivo csv 'WorldCupMatches.csv'.
- Esse dataframe não possui nomes das colunas! Use lista `nomes` (abaixo) para dar nomes às colunas (faça uma busca na web para entender como ler uma .csv com Pandas onde os índices das colunas não são especificados).
- Salve o DataFrame em uma variável
- Exiba as 5 primeiras linhas e o tipo de dado de cada coluna
- Quantas linhas possui o DataFrame?
- Remova linhas duplicadas usando `.drop_duplicates(inplace = True)`. Quantas linhas há agora?

In [ ]:
nomes = ['Year', 'Datetime', 'Stage', 'Stadium', 'City', 'HomeTeamName',
'HomeTeamGoals', 'AwayTeamGoals', 'AwayTeamName',
'WinConditions', 'Attendance', 'HalfTimeHomeGoals',
'HalfTimeAwayGoals', 'Referee', 'Assistant1', 'Assistant2',
'RoundID', 'MatchID', 'HomeTeamInitials', 'AwayTeamInitials']

In [81]:
# 5 primeiras linhas

,Year,Datetime,Stage,Stadium,City,HomeTeamName,HomeTeamGoals,AwayTeamGoals,AwayTeamName,WinConditions,Attendance,HalfTimeHomeGoals,HalfTimeAwayGoals,Referee,Assistant1,Assistant2,RoundID,MatchID,HomeTeamInitials,AwayTeamInitials
0,1930,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,4444.0,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX
1,1930,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3,0,Belgium,,18346.0,2,0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201,1090,USA,BEL
2,1930,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,24059.0,2,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA
3,1930,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,,2549.0,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1,0,France,,23409.0,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA

In [82]:
# tipo de dado de cada coluna

Year                   int64
Datetime              object
Stage                 object
Stadium               object
City                  object
HomeTeamName          object
HomeTeamGoals          int64
AwayTeamGoals          int64
AwayTeamName          object
WinConditions         object
Attendance           float64
HalfTimeHomeGoals      int64
HalfTimeAwayGoals      int64
Referee               object
Assistant1            object
Assistant2            object
RoundID                int64
MatchID                int64
HomeTeamInitials      object
AwayTeamInitials      object
dtype: object

In [83]:
# numero de linhas

852

In [84]:
# numero de linhas sem repeticao

836

#### 2) Remova as colunas listadas abaixo:

```python
['HalfTimeHomeGoals','HalfTimeAwayGoals',
 'Referee', 'Assistant1', 'Assistant2',
'RoundID', 'MatchID', 'HomeTeamInitials', 'AwayTeamInitials']
```

In [85]:
# SOLUÇÃO

rem = ['HalfTimeHomeGoals','HalfTimeAwayGoals',
 'Referee', 'Assistant1', 'Assistant2',
'RoundID', 'MatchID', 'HomeTeamInitials', 'AwayTeamInitials']

#### 3) Faça uma busca para selecionar apenas as partidas de semi-finais. Verifique primeiro a sintaxe das palavas na coluna Stage. Utilize o método .unique() na coluna Stage e identifique como semi-final está escrito. Por fim, faça uma busca para selecionar apenas as semi-finais da tabela.

In [86]:
# SOLUÇÃO

array(['Group 1', 'Group 4', 'Group 2', 'Group 3', 'Semi-finals', 'Final',
       'Preliminary round', 'Quarter-finals', 'Match for third place',
       'First round', 'Group 6', 'Group B', 'Group A', 'Group 5',
       'Group C', 'Group D', 'Group F', 'Group E', 'Round of 16',
       'Group H', 'Group G', 'Third place', 'Play-off for third place'],
      dtype=object)

In [87]:
# SOLUÇÃO

,Year,Datetime,Stage,Stadium,City,HomeTeamName,HomeTeamGoals,AwayTeamGoals,AwayTeamName,WinConditions,Attendance
15,1930,26 Jul 1930 - 14:45,Semi-finals,Estadio Centenario,Montevideo,Argentina,6,1,USA,,72886.0
16,1930,27 Jul 1930 - 14:45,Semi-finals,Estadio Centenario,Montevideo,Uruguay,6,1,Yugoslavia,,79867.0
31,1934,03 Jun 1934 - 16:30,Semi-finals,San Siro,Milan,Italy,1,0,Austria,,35000.0
32,1934,03 Jun 1934 - 16:30,Semi-finals,Nazionale PNF,Rome,Czechoslovakia,3,1,Germany,,15000.0
49,1938,16 Jun 1938 - 18:00,Semi-finals,Parc des Princes,Paris,Hungary,5,1,Sweden,,20000.0
50,1938,16 Jun 1938 - 18:00,Semi-finals,Stade V�lodrome,Marseilles,Italy,2,1,Brazil,,33000.0
97,1954,30 Jun 1954 - 18:00,Semi-finals,St. Jakob,Basel,Germany FR,6,1,Austria,,58000.0
98,1954,30 Jun 1954 - 18:00,Semi-finals,La Pontaise,Lausanne,Hungary,4,2,Uruguay,Hungary win after extra time,45000.0
132,1958,24 Jun 1958 - 19:00,Semi-finals,Nya Ullevi,Gothenburg,Sweden,3,1,Germany FR,,49471.0
133,1958,24 Jun 1958 - 19:00,Semi-finals,Rasunda Stadium,Solna,Brazil,5,2,France,,27100.0
164,1962,13 Jun 1962 - 14:30,Semi-finals,Estadio Sausalito,Vina Del Mar,Czechoslovakia,3,1,Yugoslavia,,5890.0
165,1962,13 Jun 1962 - 14:30,Semi-finals,Nacional,Santiago De Chile,Brazil,4,2,Chile,,76594.0
196,1966,25 Jul 1966 - 19:30,Semi-finals,Goodison Park,Liverpool,Germany FR,2,1,Soviet Union,,38273.0
197,1966,26 Jul 1966 - 19:30,Semi-finals,Wembley Stadium,London,England,2,1,Portugal,,94493.0
228,1970,17 Jun 1970 - 16:00,Semi-finals,Jalisco,Guadalajara,Brazil,3,1,Uruguay,,51261.0
229,1970,17 June 1970 - 16:00,Semi-finals,Estadio Azteca,Mexico City,Italy,4,3,Germany FR,Italy win after extra time,102444.0
356,1982,08 Jul 1982 - 17:15,Semi-finals,Camp Nou,Barcelona,Poland,0,2,Italy,,50000.0
357,1982,08 Jul 1982 - 21:00,Semi-finals,Ramon Sanchez Pizjuan,Seville,Germany FR,3,3,France,win on penalties (5 - 4),70000.0
408,1986,25 Jun 1986 - 12:00,Semi-finals,Jalisco,Guadalajara,France,0,2,Germany FR,,45000.0
409,1986,25 Jun 1986 - 16:00,Semi-finals,Estadio Azteca,Mexico City,Argentina,2,0,Belgium,,114500.0
460,1990,03 Jul 1990 - 20:00,Semi-finals,San Paolo,Naples,Italy,1,1,Argentina,win on penalties (3 - 4),59978.0
461,1990,04 Jul 1990 - 20:00,Semi-finals,Stadio delle Alpi,Turin,Germany FR,1,1,England,win on penalties (4 - 3),62628.0
512,1994,13 Jul 1994 - 16:00,Semi-finals,Giants Stadium,New York/New Jersey,Bulgaria,1,2,Italy,,74110.0
513,1994,13 Jul 1994 - 16:30,Semi-finals,Rose Bowl,Los Angeles,Sweden,0,1,Brazil,,91856.0
576,1998,07 Jul 1998 - 21:00,Semi-finals,Stade V�lodrome,Marseilles,Brazil,1,1,Netherlands,Brazil win on penalties (4 - 2),54000.0
577,1998,08 Jul 1998 - 21:00,Semi-finals,Stade de France,Saint-Denis,France,2,1,Croatia,,76000.0
640,2002,25 Jun 2002 - 20:30,Semi-finals,Seoul World Cup Stadium,Seoul,Germany,1,0,Korea Republic,,65256.0
641,2002,26 Jun 2002 - 20:30,Semi-finals,Saitama Stadium 2002,Saitama,Brazil,1,0,Turkey,,61058.0
704,2006,04 Jul 2006 - 21:00,Semi-finals,"FIFA World Cup Stadium, Dortmund",Dortmund,Germany,0,2,Italy,Italy win after extra time,65000.0
705,2006,05 Jul 2006 - 21:00,Semi-finals,"FIFA World Cup Stadium, Munich",Munich,Portugal,0,1,France,,66000.0
768,2010,06 Jul 2010 - 20:30,Semi-finals,Cape Town Stadium,Cape Town,Uruguay,2,3,Netherlands,,62479.0
769,2010,07 Jul 2010 - 20:30,Semi-finals,Durban Stadium,Durban,Germany,0,1,Spain,,60960.0
826,2014,08 Jul 2014 - 17:00,Semi-finals,Estadio Mineirao,Belo Horizonte,Brazil,1,7,Germany,,58141.0
829,2014,09 Jul 2014 - 17:00,Semi-finals,Arena de Sao Paulo,Sao Paulo,Netherlands,0,0,Argentina,Argentina win on penalties (2 - 4),63267.0

#### 4) Conte o número de vezes que cada estádio já recebeu um jogo de semi-final.

In [88]:
# SOLUÇÃO

Stade V�lodrome                     2
Estadio Centenario                  2
Jalisco                             2
Estadio Azteca                      2
Nya Ullevi                          1
Ramon Sanchez Pizjuan               1
Arena de Sao Paulo                  1
Nacional                            1
Giants Stadium                      1
Saitama Stadium 2002                1
Estadio Sausalito                   1
Stadio delle Alpi                   1
Parc des Princes                    1
Wembley Stadium                     1
Estadio Mineirao                    1
La Pontaise                         1
FIFA World Cup Stadium, Dortmund    1
Nazionale PNF                       1
St. Jakob                           1
Cape Town Stadium                   1
San Paolo                           1
Rasunda Stadium                     1
San Siro                            1
Goodison Park                       1
Durban Stadium                      1
FIFA World Cup Stadium, Munich      1
Stade de France                     1
Rose Bowl                           1
Camp Nou                            1
Seoul World Cup Stadium             1
Name: Stadium, dtype: int64

#### 5)** Faça um query para obter todas as partidas que o Brasil jogou contra a Alemanha.

In [89]:
# SOLUÇÃO

,Year,Datetime,Stage,Stadium,City,HomeTeamName,HomeTeamGoals,AwayTeamGoals,AwayTeamName,WinConditions,Attendance
643,2002,30 Jun 2002 - 20:00,Final,International Stadium Yokohama,Yokohama,Germany,0,2,Brazil,,69029.0
826,2014,08 Jul 2014 - 17:00,Semi-finals,Estadio Mineirao,Belo Horizonte,Brazil,1,7,Germany,,58141.0

#### 6) Vamos para o Numpy novamente . Crie uma variável para receber a matriz Numpy a partir do DataFrame.
Lembrando:
```python
nparray = dataframe.values
```

##### a) Utilizando a matriz Numpy, construa um dicionário que conta quantos gols cada país já fez em copas

In [92]:
# SOLUÇÃO

{'France': 106,
 'Mexico': 57,
 'USA': 37,
 'Belgium': 52,
 'Yugoslavia': 60,
 'Brazil': 221,
 'Romania': 30,
 'Peru': 19,
 'Argentina': 131,
 'Chile': 40,
 'Bolivia': 1,
 'Paraguay': 30,
 'Uruguay': 80,
 'Austria': 43,
 'Hungary': 87,
 'Egypt': 3,
 'Switzerland': 45,
 'Netherlands': 86,
 'Sweden': 74,
 'Germany': 93,
 'Spain': 92,
 'Italy': 128,
 'Czechoslovakia': 44,
 'Dutch East Indies': 0,
 'Cuba': 5,
 'Norway': 7,
 'Poland': 44,
 'England': 79,
 'Scotland': 25,
 'Germany FR': 131,
 'Turkey': 20,
 'Korea Republic': 31,
 'Soviet Union': 53,
 'Wales': 4,
 'Northern Ireland': 13,
 'Colombia': 26,
 'Bulgaria': 22,
 'Korea DPR': 6,
 'Portugal': 43,
 'Israel': 1,
 'Morocco': 12,
 'El Salvador': 1,
 'German DR': 5,
 'Australia': 11,
 'Zaire': 0,
 'Haiti': 2,
 'Tunisia': 8,
 'IR Iran': 2,
 'Iran': 5,
 'Cameroon': 18,
 'New Zealand': 4,
 'Algeria': 13,
 'Honduras': 3,
 'Kuwait': 2,
 'Canada': 0,
 'Iraq': 1,
 'Denmark': 27,
 'rn">United Arab Emirates': 2,
 'Costa Rica': 17,
 'rn">Republic of Ireland': 10,
 'Saudi Arabia': 9,
 'Russia': 13,
 'Greece': 5,
 'Nigeria': 20,
 'South Africa': 11,
 'Japan': 14,
 'Jamaica': 3,
 'Croatia': 21,
 'Senegal': 7,
 'Slovenia': 5,
 'Ecuador': 10,
 'China PR': 0,
 'rn">Trinidad and Tobago': 0,
 "C�te d'Ivoire": 13,
 'rn">Serbia and Montenegro': 2,
 'Angola': 1,
 'Czech Republic': 3,
 'Ghana': 13,
 'Togo': 1,
 'Ukraine': 5,
 'Serbia': 2,
 'Slovakia': 5,
 'rn">Bosnia and Herzegovina': 4}

##### b) Utilizando a matriz Numpy, construa um dicionário que conta o público (Attendance) total que o país já teve em copas.

In [93]:
# SOLUÇÃO

{'France': 2645065.0,
 'Mexico': 2546081.0,
 'USA': 1434948.0,
 'Belgium': 2040195.0,
 'Yugoslavia': 1318618.0,
 'Brazil': 5680811.0,
 'Romania': 1023420.0,
 'Peru': 411889.0,
 'Argentina': 4038215.0,
 'Chile': 1275942.0,
 'Bolivia': 229715.0,
 'Paraguay': 971335.0,
 'Uruguay': 2240601.0,
 'Austria': 993170.0,
 'Hungary': 850165.0,
 'Egypt': 110535.0,
 'Switzerland': 1426336.0,
 'Netherlands': 2626683.0,
 'Sweden': 2024201.0,
 'Germany': nan,
 'Spain': 2638930.0,
 'Italy': 4209004.0,
 'Czechoslovakia': 891114.0,
 'Dutch East Indies': 9000.0,
 'Cuba': 22000.0,
 'Norway': 390023.0,
 'Poland': 1254183.0,
 'England': 2940845.0,
 'Scotland': 783776.0,
 'Germany FR': 3273775.0,
 'Turkey': 383186.0,
 'Korea Republic': 1401968.0,
 'Soviet Union': 1237114.0,
 'Wales': 89526.0,
 'Northern Ireland': 312369.0,
 'Colombia': 885233.0,
 'Bulgaria': 1160335.0,
 'Korea DPR': 247613.0,
 'Portugal': 1266789.0,
 'Israel': 40168.0,
 'Morocco': 420697.0,
 'El Salvador': 355742.0,
 'German DR': 287965.0,
 'Australia': 555535.0,
 'Zaire': 94900.0,
 'Haiti': 104200.0,
 'Tunisia': 525357.0,
 'IR Iran': 234159.0,
 'Iran': 199762.0,
 'Cameroon': 1068503.0,
 'New Zealand': 194950.0,
 'Algeria': nan,
 'Honduras': 327212.0,
 'Kuwait': 94743.0,
 'Canada': 93500.0,
 'Iraq': 147763.0,
 'Denmark': 654045.0,
 'rn">United Arab Emirates': 129793.0,
 'Costa Rica': 683018.0,
 'rn">Republic of Ireland': 650601.0,
 'Saudi Arabia': 701859.0,
 'Russia': 521941.0,
 'Greece': 469610.0,
 'Nigeria': 852461.0,
 'South Africa': 390299.0,
 'Japan': 749774.0,
 'Jamaica': 122700.0,
 'Croatia': 740670.0,
 'Senegal': 223722.0,
 'Slovenia': 218791.0,
 'Ecuador': 549877.0,
 'China PR': 107572.0,
 'rn">Trinidad and Tobago': 149959.0,
 "C�te d'Ivoire": 491842.0,
 'rn">Serbia and Montenegro': 161000.0,
 'Angola': 126000.0,
 'Czech Republic': 147000.0,
 'Ghana': 636950.0,
 'Togo': 158000.0,
 'Ukraine': 260000.0,
 'Serbia': 114963.0,
 'Slovakia': 165888.0,
 'rn">Bosnia and Herzegovina': 163248.0}

#### c) Insira os dois dicionários acima em outro dicionário para criar um DataFrame onde cada dicionário representa uma coluna. Salve o DataFrame em um arquivo .csv.

In [94]:
# SOLUÇÃO

                            gols    publico
Algeria                       13        NaN
Angola                         1   126000.0
Argentina                    131  4038215.0
Australia                     11   555535.0
Austria                       43   993170.0
Belgium                       52  2040195.0
Bolivia                        1   229715.0
Brazil                       221  5680811.0
Bulgaria                      22  1160335.0
Cameroon                      18  1068503.0
Canada                         0    93500.0
Chile                         40  1275942.0
China PR                       0   107572.0
Colombia                      26   885233.0
Costa Rica                    17   683018.0
Croatia                       21   740670.0
Cuba                           5    22000.0
Czech Republic                 3   147000.0
Czechoslovakia                44   891114.0
C�te d'Ivoire                 13   491842.0
Denmark                       27   654045.0
Dutch East Indies              0     9000.0
Ecuador                       10   549877.0
Egypt                          3   110535.0
El Salvador                    1   355742.0
England                       79  2940845.0
France                       106  2645065.0
German DR                      5   287965.0
Germany                       93        NaN
Germany FR                   131  3273775.0
...                          ...        ...
Peru                          19   411889.0
Poland                        44  1254183.0
Portugal                      43  1266789.0
Romania                       30  1023420.0
Russia                        13   521941.0
Saudi Arabia                   9   701859.0
Scotland                      25   783776.0
Senegal                        7   223722.0
Serbia                         2   114963.0
Slovakia                       5   165888.0
Slovenia                       5   218791.0
South Africa                  11   390299.0
Soviet Union                  53  1237114.0
Spain                         92  2638930.0
Sweden                        74  2024201.0
Switzerland                   45  1426336.0
Togo                           1   158000.0
Tunisia                        8   525357.0
Turkey                        20   383186.0
USA                           37  1434948.0
Ukraine                        5   260000.0
Uruguay                       80  2240601.0
Wales                          4    89526.0
Yugoslavia                    60  1318618.0
Zaire                          0    94900.0
rn">Bosnia and Herzegovina     4   163248.0
rn">Republic of Ireland       10   650601.0
rn">Serbia and Montenegro      2   161000.0
rn">Trinidad and Tobago        0   149959.0
rn">United Arab Emirates       2   129793.0

[83 rows x 2 columns]

** faça upload de um notebook com a solução da questão 5) (pode fazer upload de todo homework se quiser) no google drive no diretório: <br><br>
[http://tiny.cc/4quwdz](http://tiny.cc/4quwdz)

O nome do notebook deve ser: <br><br>
_seuprimeironome-seuultimonome-modulo3.ipynb_

Por exemplo: _gustavo-nonato-modulo3.ipynb_